# Generated by Django 5.0.1 on 2024-01-21 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': ' آدرس', 'verbose_name_plural': 'آدرس ها  '},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': ' کاربر', 'verbose_name_plural': '  کاربران  '},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.CharField(max_length=100, verbose_name='آدرس تکمیلی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=12, verbose_name='کدپستی'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_operator',
            field=models.BooleanField(default=False, verbose_name='اپراتور'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_product_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر محصول'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='ناظر'),
        ),
    ]
