# Generated by Django 5.0.1 on 2024-01-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_myuser_created_myuser_updated_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
