# Generated by Django 4.2 on 2024-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_address_is_active_address_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
    ]
