# Generated by Django 4.2 on 2024-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_address_is_active_alter_address_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=100, verbose_name='کدپستی'),
        ),
    ]
