# Generated by Django 5.0.1 on 2024-01-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='cash_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='maximum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='cash_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='maximum',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='percentage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
