# Generated by Django 5.0.1 on 2024-01-21 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_discount_name_discountcode_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف ها'},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='product.comment', verbose_name='پاسخ به'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='cash_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='نقدی'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='maximum',
            field=models.FloatField(default=0, verbose_name='بیشینه تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درصدی'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='cash_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='نقدی'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name=' تاریخ انقضاء'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='maximum',
            field=models.FloatField(default=0, verbose_name='بیشینه تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درصدی'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('سفید', 'سفید'), ('مشکی', 'مشکی'), ('آبی', 'آبی'), ('قرمز', 'قرمز'), ('سبز', 'سبز')], max_length=10, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_count',
            field=models.PositiveIntegerField(verbose_name='تعداد کل'),
        ),
    ]
