# Generated by Django 5.0.1 on 2024-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_image_created_image_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
