# Generated by Django 4.2 on 2024-02-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_image_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
    ]
