# Generated by Django 4.2 on 2024-02-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_address_order_created_order_is_active_and_more'),
        ('order', '0004_alter_order_created_alter_orderitem_created'),
    ]

    operations = [
    ]
