# Generated by Django 4.2 on 2024-02-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merge_20240215_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
