# Generated by Django 4.2 on 2024-02-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_address_is_active_alter_address_is_deleted_and_more'),
        ('order', '0006_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.address', verbose_name='آدرس '),
            preserve_default=False,
        ),
    ]
